version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
